legal_research_task:
  description: >
    Find SHORT legal facts about {topic} for India.
    Focus on:
    1. Top 2-3 key laws/acts with 2-3 line definitions
    2. Basic requirements (3-4 points)
    3. Must include detailed online/offline step-by-step process
    4. Official government links for India
    Keep it VERY SHORT - maximum 200 words total.
    Current year is {current_year}.
  expected_output: >
    SHORT summary with:
    - 2-3 main laws with definitions (2-3 lines each)
    - 3-4 key requirements
    - Detailed online and offline steps with portals/locations
    - Official Indian government links
    Maximum 200 words. Use bullet points only.
  agent: legal_researcher

legal_analysis_task:
  description: >
    Make {topic} research into SUPER SHORT summary for India.
    Include:
    1. What it is (one sentence)
    2. Main requirement (one line)
    3. Detailed online vs offline process steps
    4. Important warning
    Maximum 150 words total.
  expected_output: >
    VERY SHORT summary:
    - What: [one sentence]
    - Need: [main requirement]
    - Online: [detailed online process steps with portals]
    - Offline: [detailed offline process steps with locations]
    - Warning: [key warning]
    Maximum 150 words.
  agent: legal_analyst

procedure_guidance_task:
  description: >
    Create SHORT step-by-step guide for {topic} in India with:
    1. Detailed online steps (4-6 steps with portal names)
    2. Detailed offline steps (4-6 steps with office locations)
    3. Required documents (5 max)
    4. Official links for applications
    5. Timeline and fees
    Keep it under 250 words.
  expected_output: >
    SHORT guide:
    
    **Online Process:**
    1. [Detailed step with specific portal/website]
    2. [Detailed step with specific portal/website]
    3. [Detailed step with specific portal/website]
    4. [Additional steps as needed]
    
    **Offline Process:**
    1. [Detailed step with specific office location]
    2. [Detailed step with specific office location]
    3. [Detailed step with specific office location]
    4. [Additional steps as needed]
    
    **Documents:** [5 max]
    **Timeline:** [duration]
    **Fees:** [amount]
    **Links:** [official government links]
    
    Maximum 250 words. Save as markdown.
  agent: procedure_specialist
